research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst


meeting_minutes_summary_task:
  description: >
    Summarize the meeting transcript into a summary with the following transcript:
    {transcript}

    Write the summary to a file called "summary.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    Write the action items to a file called "action_items.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    I would like you to return the action items from the meeting transcript in the following format:
    - Action item 1
    - Action item 2
    - ...

    I would also like you to analyze the sentiment of the meeting transcript and write it to a file called "sentiment.txt" in the "meeting_minutes" directory.  This is provided by the tool.

  expected_output: >
    A summary of the meeting transcript and a list of action items.
  agent: meeting_minutes_summarizer